import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/layouts/Footer";
import "/node_modules/primeflex/primeflex.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeicons/primeicons.css";
import Navbar from "@/layouts/Navbar";
import Sidebar from "@/layouts/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <main>
          <div className="grid">
            <div className="col-4">
              <Sidebar />
            </div>
            <div className="col">{children}</div>
          </div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
